var searchData=
[
  ['helpmenu',['helpMenu',['../_declar__funz_8h.html#ac711f79a35ebd31f89aebf9ef213d904',1,'helpMenu():&#160;FunzBiginEnd.cpp'],['../_funz_bigin_end_8cpp.html#ac711f79a35ebd31f89aebf9ef213d904',1,'helpMenu():&#160;FunzBiginEnd.cpp']]],
  ['histogram_5f2d',['Histogram_2D',['../_declar__funz_8h.html#a029b3ee8e7c2c3c50fdbbe38fd1db51d',1,'Histogram_2D(std::string name_info[], std::string name_files_tau_mod[], int save_, int cont_glob_sim):&#160;Declar_funz.h'],['../_histogram__2_d__gnuplot_8cpp.html#a2e7e6a0aa46aad26af152a04c2367b99',1,'Histogram_2D(string name_info_mod[], string name_files_tau_mod[], int save_, int cont_glob_sim):&#160;Histogram_2D_gnuplot.cpp']]],
  ['histogram_5f3d_5ffunzc',['Histogram_3D_FunzC',['../_histogram_c__3_d_8cpp.html#adbf821895dfbe391ad6111dd6f834cdd',1,'HistogramC_3D.cpp']]],
  ['histogram_5f3d_5fgnuplot',['histogram_3D_gnuplot',['../gnuplot__3_d_8h.html#a436c21a1802030ebb09d573f2429eedc',1,'histogram_3D_gnuplot(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, std::vector&lt; std::vector&lt; double &gt; &gt; x, std::vector&lt; std::vector&lt; double &gt; &gt; y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, std::string name_file):&#160;gnuplot_3D.h'],['../_histogram__3_d__gnuplot_8cpp.html#ac72fd775bb1e8fe4959b6a77c58ec6e0',1,'histogram_3D_gnuplot(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, vector&lt; vector&lt; double &gt; &gt; x, vector&lt; vector&lt; double &gt; &gt; y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, string name_file_info):&#160;Histogram_3D_gnuplot.cpp']]],
  ['histogram_5f3d_5fgnuplotv2',['histogram_3D_gnuplotV2',['../gnuplot__3_d_8h.html#a6bce835d3e59a0e44d2a9b4403699b4f',1,'histogram_3D_gnuplotV2(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;x, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int MaxDom, int cont_sim, std::string name_file):&#160;gnuplot_3D.h'],['../histogram__3d__gnuplot_v2_8cpp.html#a95a0d6ff2cbcd749b52e66d3bc4a937f',1,'histogram_3D_gnuplotV2(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, vector&lt; vector&lt; double &gt; &gt; &amp;x, vector&lt; vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int risp_Max, int cont_sim, string name_file_info):&#160;histogram_3d_gnuplotV2.cpp']]],
  ['histogram_5f3d_5fgnuplotv2multithread',['histogram_3D_gnuplotV2MultiThread',['../gnuplot__3_d_8h.html#a3083d7ffb85d4eda0d20fec2b0ad794d',1,'histogram_3D_gnuplotV2MultiThread(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;x, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int MaxDom, int cont_sim, std::string name_file):&#160;gnuplot_3D.h'],['../histogram__3d__gnuplot_v2_8cpp.html#ad058502964ee18fc5167f2c29808cb9d',1,'histogram_3D_gnuplotV2MultiThread(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, vector&lt; vector&lt; double &gt; &gt; &amp;x, vector&lt; vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int risp_Max, int cont_sim, string name_file_info):&#160;histogram_3d_gnuplotV2.cpp']]],
  ['histogram_5f3d_5fgnuplotv2multithreadv2',['histogram_3D_gnuplotV2MultiThreadV2',['../histogram3_d_multi_thread_v2_8hpp.html#a823d8ffffd5d9fdae1fe104671117b38',1,'histogram_3D_gnuplotV2MultiThreadV2(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;x, std::vector&lt; std::vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int risp_Max, int cont_sim, std::string name_file):&#160;histogram3DMultiThreadV2.hpp'],['../gnuplot__large__population__iteracting_8cpp.html#aea1138f60f02a5f10e6808a9fdc7a2f0',1,'histogram_3D_gnuplotV2MultiThreadV2(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, vector&lt; vector&lt; double &gt; &gt; &amp;x, vector&lt; vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int risp_Max, int cont_sim, string name_info):&#160;histogram3DMultiThreadV2.cpp'],['../histogram3_d_multi_thread_v2_8cpp.html#abe922b6760863c741c7e3c16b12600fb',1,'histogram_3D_gnuplotV2MultiThreadV2(double max_x, double max_y, double min_x, double min_y, int n_dx, int n_dy, double dx, double dy, vector&lt; vector&lt; double &gt; &gt; &amp;x, vector&lt; vector&lt; double &gt; &gt; &amp;y, int n_c, int dim_col_t, int n_salti_colonne, Funz_C *f, double &amp;maxC, int risp_Max, int cont_sim, string name_file_info):&#160;histogram3DMultiThreadV2.cpp']]],
  ['histogram_5fdynamic',['Histogram_Dynamic',['../gnuplot__3_d_8h.html#a1c482f9a512f42a85cb00f3090999a60',1,'Histogram_Dynamic(std::string name, std::string name_dynamic, int sim_cont):&#160;Hystogram_Dynamic.cpp'],['../_hystogram___dynamic_8cpp.html#a169b5d9747ee5dae166c601eb95b394e',1,'Histogram_Dynamic(std::string name, std::string name_dynamic, int cont_sim):&#160;Hystogram_Dynamic.cpp']]]
];
