var dir_2b453e552fe2aa3a003dd5690ae5c018 =
[
    [ "baricentro_plot.cpp", "baricentro__plot_8cpp.html", "baricentro__plot_8cpp" ],
    [ "Cancell_histFile.cpp", "_cancell__hist_file_8cpp.html", "_cancell__hist_file_8cpp" ],
    [ "filmato_3D_gnuplot.cpp", "filmato__3_d__gnuplot_8cpp.html", "filmato__3_d__gnuplot_8cpp" ],
    [ "filmato_3D_gnuplot_gif.cpp", "filmato__3_d__gnuplot__gif_8cpp.html", "filmato__3_d__gnuplot__gif_8cpp" ],
    [ "filmato_3D_gnuplotMultiThread.cpp", "filmato__3_d__gnuplot_multi_thread_8cpp.html", "filmato__3_d__gnuplot_multi_thread_8cpp" ],
    [ "gnuplot_large_population.cpp", "gnuplot__large__population_8cpp.html", "gnuplot__large__population_8cpp" ],
    [ "gnuplot_large_population_iteracting.cpp", "gnuplot__large__population__iteracting_8cpp.html", "gnuplot__large__population__iteracting_8cpp" ],
    [ "gnuplot_run.cpp", "gnuplot__run_8cpp.html", "gnuplot__run_8cpp" ],
    [ "gnuplot_run_multiplot.cpp", "gnuplot__run__multiplot_8cpp.html", "gnuplot__run__multiplot_8cpp" ],
    [ "gnuplot_single_3.cpp", "gnuplot__single__3_8cpp.html", "gnuplot__single__3_8cpp" ],
    [ "gnuplot_single_film.cpp", "gnuplot__single__film_8cpp.html", "gnuplot__single__film_8cpp" ],
    [ "gnuplotFunzInternalDynalmic.cpp", "gnuplot_funz_internal_dynalmic_8cpp.html", "gnuplot_funz_internal_dynalmic_8cpp" ],
    [ "histogram3DMultiThreadV2.cpp", "histogram3_d_multi_thread_v2_8cpp.html", "histogram3_d_multi_thread_v2_8cpp" ],
    [ "Histogram_2D_gnuplot.cpp", "_histogram__2_d__gnuplot_8cpp.html", "_histogram__2_d__gnuplot_8cpp" ],
    [ "Histogram_3D_gnuplot.cpp", "_histogram__3_d__gnuplot_8cpp.html", "_histogram__3_d__gnuplot_8cpp" ],
    [ "histogram_3d_gnuplotV2.cpp", "histogram__3d__gnuplot_v2_8cpp.html", "histogram__3d__gnuplot_v2_8cpp" ],
    [ "HistogramC_3D.cpp", "_histogram_c__3_d_8cpp.html", "_histogram_c__3_d_8cpp" ],
    [ "Hystogram_Dynamic.cpp", "_hystogram___dynamic_8cpp.html", "_hystogram___dynamic_8cpp" ],
    [ "lunch_gnuplot.cpp", "lunch__gnuplot_8cpp.html", "lunch__gnuplot_8cpp" ],
    [ "multiplot_film_snapshots.cpp", "multiplot__film__snapshots_8cpp.html", "multiplot__film__snapshots_8cpp" ],
    [ "setSizesTitles.cpp", "set_sizes_titles_8cpp.html", "set_sizes_titles_8cpp" ],
    [ "stamp_gnuplot_instruction.cpp", "stamp__gnuplot__instruction_8cpp.html", "stamp__gnuplot__instruction_8cpp" ],
    [ "Statistical_Analysis.cpp", "_statistical___analysis_8cpp.html", "_statistical___analysis_8cpp" ],
    [ "Verifica_gnuplot.cpp", "_verifica__gnuplot_8cpp.html", "_verifica__gnuplot_8cpp" ],
    [ "writeHistToFileMultiT.cpp", "write_hist_to_file_multi_t_8cpp.html", "write_hist_to_file_multi_t_8cpp" ]
];